name: CMake on a single platform

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  BUILD_TYPE: Release
  CC: gcc
  CXX: g++

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./tests

